apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: c4d-webserver
  namespace: c4d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - image: gcr.io/pc-api-6479467557629758909-343/github.com/yes-soft-de/c4d
          imagePullPolicy: Always
          name: php-apache
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/upload/image
              name: pvc-sym-m
      volumes:
        - name: pvc-sym-m
          persistentVolumeClaim:
            claimName: c4d-pvc-sym-uploud
