name: c4d
description: A new Flutter application.

publish_to: 'none'

version: 1.0.9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_datetime_picker: ^1.4.0

  # Localization Library
  flutter_localizations:
    sdk: flutter

  # Fonts
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.11.0

  # DI
  provider: ^4.3.2+2

  # Crypto for SHA1
  crypto: ^2.1.5

  # Dependency injection
  inject:
    git:
      url: https://github.com/yes-soft-de/inject.dart.git
      path: package/inject

  # Camera
  image_picker: ^0.6.7+14

  # Video
  video_player: ^1.0.0

  # Paths
  path_provider: ^1.6.24

  # Shared Prefs
  shared_preferences: ^0.5.12+4

  # Open Url in Chrome
  url_launcher: ^5.7.0

  # Network Agent
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  dio_http_cache: ^0.2.11
  dio_firebase_performance: ^0.2.0

  # Pair and Other Types
  analyzer_plugin: ^0.3.0
  timeago: ^2.0.29

  # String validation
  validators: ^2.0.1

  # Svg Loader
  flutter_svg: ^0.19.1

  # Streams and RX
  rxdart: ^0.24.1

  # ORM, Database SQL
  sqfentity: ^1.4.0+3

  # Firebase Libs
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.4+1
  firebase_analytics: ^6.3.0
  firebase_remote_config: ^0.4.3
  cloud_firestore: ^0.14.4
  firebase_performance: ^0.4.0
  firebase_messaging: ^7.0.0
  firebase_crashlytics: ^0.2.4

  # Google Sign In
  google_sign_in: ^4.5.6
  sign_in_with_apple: ^2.5.4

  # Localization
  gen_lang: 0.1.3

  # Internationalization
  intl: ^0.16.1
  intl_translation: ^0.17.10
  intl_utils: ^1.9.0

  # Toasts
  fluttertoast: ^7.1.1

  # UUID
  uuid: ^2.2.2

  # ProgressBar
  step_progress_indicator: ^0.2.5+8

  # Maps and Locations
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1
  location: ^3.1.0

  # Deep Linking, for quick send
  uni_links: ^0.4.0

  # Charts and Diagrams
  charts_flutter: ^0.9.0

  # Credit Card and Payment
  flutter_credit_card: ^0.1.3
  stripe_payment : ^1.0.9

  # Lottie and Flare for animations
  lottie: ^0.7.0+1
  flare_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For Testing
  flutter_driver:
    sdk: flutter
  test: ^1.15.5
  flutter_gherkin: ^1.1.9

  # For DI
  build_runner: ^1.10.1

  # DI Framework
  inject_generator:
    git:
      url: https://github.com/yes-soft-de/inject.dart.git
      path: package/inject_generator

  # Generate Language Files
  lang_table: 0.2.0

  # Icons Generator
  flutter_launcher_icons: "^0.7.3"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

flutter_intl:
  enabled: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"